USE [master]
GO
/****** Object:  Database [Smithy]    Script Date: 18.05.2023 13:52:46 ******/
CREATE DATABASE [Smithy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Smithy', FILENAME = N'D:\SQLSERVER\MSSQL15.SQLEXPRESS\MSSQL\DATA\Smithy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Smithy_log', FILENAME = N'D:\SQLSERVER\MSSQL15.SQLEXPRESS\MSSQL\DATA\Smithy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Smithy] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Smithy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Smithy] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Smithy] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Smithy] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Smithy] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Smithy] SET ARITHABORT OFF 
GO
ALTER DATABASE [Smithy] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Smithy] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Smithy] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Smithy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Smithy] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Smithy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Smithy] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Smithy] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Smithy] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Smithy] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Smithy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Smithy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Smithy] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Smithy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Smithy] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Smithy] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Smithy] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Smithy] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Smithy] SET  MULTI_USER 
GO
ALTER DATABASE [Smithy] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Smithy] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Smithy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Smithy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Smithy] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Smithy] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Smithy] SET QUERY_STORE = OFF
GO
USE [Smithy]
GO
/****** Object:  Table [dbo].[AccountData]    Script Date: 18.05.2023 13:52:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AccountData](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](20) NULL,
	[password] [varchar](30) NULL,
	[permlvl] [int] NULL,
	[created_at] [datetime] NULL,
	[userid] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[login] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserData]    Script Date: 18.05.2023 13:52:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserData](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](20) NULL,
	[surname] [varchar](30) NULL,
	[division] [varchar](50) NULL,
	[rank] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AccountData] ADD  DEFAULT ((1)) FOR [permlvl]
GO
ALTER TABLE [dbo].[AccountData] ADD  DEFAULT (sysdatetime()) FOR [created_at]
GO
ALTER TABLE [dbo].[AccountData]  WITH CHECK ADD FOREIGN KEY([userid])
REFERENCES [dbo].[UserData] ([id])
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [Smithy] SET  READ_WRITE 
GO
